#$Id$

__END__
=encoding euc-jp

=head1 NAME

clear.pl - PyukiWiki / YukiWiki プラグイン

=head1 概要

 &clear;

=head1 重要度

★★☆☆☆

=head1 説明

指定した位置に、CSSのクラスの'clear' (clear:both) を挿入します。

テキストの回りこみが解除できます。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/clear

L<http://pyukiwiki.info/PyukiWiki/Plugin/Standard/clear/>

=item PyukiWiki CVS

L<http://osdn.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/clear.pl?view=log>

L<http://osdn.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/plugin/clear.pl?view=log>

L<http://cvs.pyukiwiki.info/cgi-bin/cvsweb.cgi/PyukiWiki-Devel/plugin/clear.pl?view=log>

L<http://cvs.pyukiwiki.info/cgi-bin/cvsweb.cgi/PyukiWiki-Devel-UTF8/plugin/clear.pl?view=log>

=back

=head1 著者

=over 4

=item ななみ

L<http://nano.daiba.cx/> etc...

=item PyukiWiki Developers Team

L<http://pyukiwiki.info/>

=back

=head1 ライセンス

(C)2005-2015 by ななみ.

(C)2005-2015 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
