#$Id$

__END__
=encoding utf-8

=head1 NAME

multicomment.inc.pl - PyukiWiki プラグイン

=head1 概要

 #multicomment(label=コメントする=,name=お名前=,url=Webページ（任意）=http://,mail=メールアドレス（任意）=,textarea=コメント=)

=head1 重要度

★☆☆☆☆

=head1 説明

高機能コメントフォームを表示して、訪問者からのコメント入力を受け付ける

=head1 使用方法

 #multicomment(label=コメントする=,name=お名前=,url=Webページ（任意）=http://,mail=メールアドレス（任意）=,textarea=コメント=)

=head1 設定

=head2 pyukiwiki.ini.cgiの設定

=over 4

=item $::writefrozenplugin

１の場合、凍結されたページでも書き込めるようにする。

=back

=head2 multicomment.inc.plの設定

=over 4

=item my $multicomment_format
Wiki文法でコメントを挿入する書式

\x08はセパレーターなので、削除しないで下さい。

=item $multicomment::noname

1 の場合、名前なしで処理しない

=item $multicomment::nodata

1 の場合、コメントなしでエラーとする

=back

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/multicomment

L<http://pyukiwiki.info/PyukiWiki/Plugin/Standard/multicomment/>

=item PyukiWiki CVS

L<http://osdn.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/multicomment.inc.pl?view=log>

L<http://osdn.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/plugin/multicomment.inc.pl?view=log>

L<http://cvs.pyukiwiki.info/cgi-bin/cvsweb.cgi/PyukiWiki-Devel/plugin/multicomment.inc.pl?view=log>

L<http://cvs.pyukiwiki.info/cgi-bin/cvsweb.cgi/PyukiWiki-Devel-UTF8/plugin/multicomment.inc.pl?view=log>

=back

=head1 著者

=over 4

=item ななみ

L<http://nano.daiba.cx/> etc...

=item PyukiWiki Developers Team

L<http://pyukiwiki.info/>

=back

=head1 ライセンス

(C)2005-2015 by ななみ.

(C)2005-2015 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
